### PR TITLE
Fix docker watching in rails

### LINKED ISSUE #103: Rails code updates not applied in docker dev env
I am not able to see changes in some rails code propagate to the browser when running in a docker container.

Steps to repro: 

 1. Run the app in a docker container
 1. Update an API stub response (e.g.; `{ ... name: 'Dave' }` ==> `{ ... name: 'Danny' }`)
 1. Refresh browser

#### Expected: 

The XHR response payload should have the updated record (Danny)

#### Actual:

No change. (Dave)

### Notes:

I can produce the desired behavior by executing the docker run [COMMAND] [ARG...] from the start script. (Not in docker.) This indicates it may be a file-watching thing just like as with javascript workarounds.

NO propagation in Docker:

rails-no-update

The _desired_ developer experience working on local workstation:

rails-no-update2

### PR DESCRIPTION
**Pull request by eckdanny-osi**
Closes #103.

### CODE REVIEW

File: app/controllers/api/cases_controller.rb [hunk 1]
```diff
@@ -12,7 +12,7 @@ def cases_by_user
     private
 
     def names
-      %w[Alice Bob Carl Dave Earl Frank Gregg Henry Ivan Johnny]
+      %w[Alice Bob Carl DOUG Earl Frank Gregg Henry Ivan Johnny]
```
Comment (eckdanny-osi) [inline app/controllers/api/cases_controller.rb]: deltas out of scope. remove.

File: app/javascript/clientIdPage/ClientIdPage.js [hunk 2]
```diff
@@ -1,46 +0,0 @@
-import React from 'react';
```
Comment (eckdanny-osi) [inline app/javascript/clientIdPage/ClientIdPage.js]: fixing #102 is a separate concern. Remove from PR.

File: app/javascript/packs/clients.js [hunk 3]
```diff
@@ -0,0 +1 @@
+import '../clients/clientIdPage';
```
Comment (eckdanny-osi) [inline app/javascript/packs/clients.js]: fixing #102 is a separate concern. remove from PR.

File: app/javascript/packs/clients/client.js [hunk 4]
```diff
@@ -1,3 +0,0 @@
-import ClientIdPage from 'Clients/clientIdPage';
```
Comment (eckdanny-osi) [inline app/javascript/packs/clients/client.js]: fixing #102 is a separate concern. remove from PR.

File: app/views/clients/show.html.erb [hunk 5]
```diff
@@ -1,5 +1,5 @@
 <div id="root">
-<%= javascript_pack_tag 'clients/client' %>
+<%= javascript_pack_tag 'clients' %>
```
Comment (eckdanny-osi) [inline app/views/clients/show.html.erb]: fixing #102 is a separate concern. remove from PR.
