### PR TITLE
Fix develop in docker set up

### LINKED ISSUE #88: Support Config for developing in Docker
Now that `rails/webpacker` exposes the `watchOptions` in config, we need a way to opt-in to the docker setup. This was naively attempted in [Procfile.docker.dev](https://github.com/ca-cwds/case-management/blob/master/Procfile.docker.dev#L2) with `--watch-poll` and `--watch-aggregate-timeout` command flags. (The flags _were_ identified in `webpack-dev-server --help` ouput as legitimate, but setting these properties via flags is not supported. This has since been fixed upstream.)

We still need a way to opt-in to our Docker-specific configuration WITHOUT losing the default `developement` configuration.

Start by defining the docker-specific config in `config/webpacker.yml` by extending `develop`.

### PR DESCRIPTION
**Pull request by eckdanny-osi**
closes #88

### CODE REVIEW

File: app/javascript/packs/client.js [hunk 1]
```diff
@@ -1,3 +1 @@
-import ClientIdPage from '../clientIdPage';
-
-export default ClientIdPage;
+import '../clientIdPage';
```
Comment (edgibbs) [inline app/javascript/packs/client.js]: Ahh got it see the redundant declaration in the file.

Comment (eckdanny) [reply app/javascript/packs/client.js]: `packs` import our js module(s) for the side effects (e.g.; bootstrapping a react app in `div#root`. No good reason to export anything here.

**Comment by eckdanny-osi** [comment]
#85 has bee merged. Handled merge manually.
